NAME	= libft.a

SRC		= ft_isalpha.c ft_isdigit.c ft_isalnum.c\
		  ft_isascii.c ft_isprint.c ft_strlen.c\
		  ft_memset.c ft_bzero.c ft_memcpy.c\
		  ft_memmove.c ft_strlcpy.c ft_strlcat.c\
		  ft_toupper.c ft_tolower.c ft_strchr.c\
		  ft_strrchr.c #ft_strncmp.c memcmp.c\
		  ft_strnstr.c ft_atoi.c ft_calloc.c\
		  ft_strdup.c ft_substr.c ft_strjoin.c\
		  ft_strtrim.c ft_split.c ft_itoa.c\
		  ft_strmapi.c ft_striteri.c ft_putchar_fd.c\
		  ft_putstr.c ft_putendl_fd.c ft_putnbr_fd

CFLAGS	= -Wall -Werror -Wextra
CC		= gcc
OBJ		= $(SRC:.c=.o)

.PHONY: all clean fclean re

all: $(NAME)

$(NAME): $(OBJ)
	ar -rcs $(NAME) $(OBJ)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all
